version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: sudo mysql -u root -p MYSQL_ROOT_PASSWORD
            - run: npm run build-schema
            - run: npm run set-data
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
